on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

name: "Build & Release"

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      # 1. Kiểm tra mã nguồn từ repository
      - uses: actions/checkout@v3

      # 2. Cài đặt Java (cho build Android)
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17.x'

      # 3. Thiết lập Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.1

      # 4. Cấu hình Flutter và kiểm tra môi trường
      - run: flutter config --no-analytics
      - run: flutter doctor

      # 5. Cài dependencies
      - run: flutter pub get

      # 6. Chạy kiểm thử tự động
      - run: flutter test

      # 7. Build APK debug và AAB
      - run: flutter build apk --debug --split-per-abi
      - run: flutter build appbundle --release
      - run: flutter build apk

      # 8. Push APK Debug lên GitHub Releases
      - name: Push to Debug Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          tag: v1.0.${{ github.run_number }}-debug
          token: ${{ secrets.TOKEN_CICD }}

      # 9. Push APK Release và AAB lên GitHub Releases
      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/apk/release/*.apk
            build/app/outputs/bundle/release/*.aab
          tag: v1.0.${{ github.run_number }}-release
          token: ${{ secrets.TOKEN_CICD }}

      # 10. Deploy APK lên Firebase App Distribution
      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: Deploy APK to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_TOKEN }}
          group: testers
          file: build/app/outputs/apk/release/app-release.apk